gx: add cluster command and commands usage

diff --git a/.local/bin/gx b/.local/bin/gx
--- a/.local/bin/gx
+++ b/.local/bin/gx
@@ -18,28 +18,131 @@ print_usage() {
   $bin_name [ login ] <installation> [ <separator> <cluster> ]         Create kubeconfig for the given installation or cluster
   $bin_name ssh       <installation> [ <separator> <cluster> ] <node>  SSH into the given node
   $bin_name open      <installation>                           <app>   Get the URL for the given app
+  $bin_name cluster   [ options ] <action> [ args ... ]                Manage clusters, actions: create, delete, list, status, keep
 
 Arguments:
-  <installation>  installation name
-  <separator>     any non alphanumeric character surrounded by spaces or not. i.e. can be a single space
-  <cluster>       cluster name
-  <node>          node hostname, or ip
-  <app>           app name
+  <installation>  Name of the installation to create kubeconfig for, or SSH into.
+  <separator>     Any non alphanumeric character surrounded by spaces or not. i.e. can be a single space.
+  <cluster>       Name of the cluster to create kubeconfig for or SSH into (optional).
+  <node>          Hostname or IP address of the node to SSH into.
+  <app>           Name of the app to open.
+
+Options:
+  -h, --help      Show help message for any command and exit
+
+Examples:
+  $bin_name my-installation my-cluster
+  $bin_name ssh my-installation my-cluster ip-11-1-111-11
+  $bin_name open my-installation my-app
+  $bin_name cluster create"
+}
+
+print_login_usage() {
+  bin_name="$(basename "$0")"
+  echo "Usage:
+  $bin_name [ login ] <installation> [ <separator> <cluster> ]  Create kubeconfig for the given installation or cluster
+
+Arguments:
+  <installation>  Name of the installation to create kubeconfig for.
+  <separator>     Any non-alphanumeric character surrounded by spaces or not. i.e. can be a single space.
+  <cluster>       Name of the cluster to create kubeconfig for (optional).
+
+Options:
+  -h, --help      Show this help message and exit
 
 Examples:
   $bin_name my-installation
   $bin_name my-installation my-cluster
-  $bin_name my-installation-my-cluster
-  $bin_name my-installation / my-cluster
-  $bin_name ssh my-installation ip-11-1-111-11
-  $bin_name ssh my-installation my-cluster ip-11-1-111-11
+  $bin_name login my-installation
+  $bin_name login my-installation my-cluster
+  $bin_name login my-installation-my-cluster
+  $bin_name login my-installation / my-cluster"
+}
+
+print_open_usage() {
+  bin_name="$(basename "$0")"
+  echo "Usage:
+  $bin_name open <installation> <app>  Get the URL for the given app
+
+Arguments:
+  <installation>  Name of the installation to open the app in.
+  <app>           Name of the app to open.
+
+Options:
+  -h, --help      Show this help message and exit
+
+Examples:
   $bin_name open my-installation my-app"
 }
 
-exit_usage() {
-  echo "ERROR: Missing arguments" 1>&2
-  print_usage
-  exit 1
+print_ssh_usage() {
+  bin_name="$(basename "$0")"
+  echo "Usage:
+  $bin_name ssh <installation> [ <separator> <cluster> ] <node>  SSH into the given node
+
+Arguments:
+  <installation>  Name of the installation to SSH into.
+  <separator>     Any non-alphanumeric character surrounded by spaces or not. i.e. can be a single space.
+  <cluster>       Name of the cluster to SSH into (optional).
+  <node>          Hostname or IP address of the node to SSH into.
+
+Options:
+  -h, --help      Show this help message and exit
+
+Examples:
+  $bin_name ssh my-installation ip-11-1-111-11
+  $bin_name ssh my-installation my-cluster ip-11-1-111-11
+  $bin_name ssh my-installation / my-cluster ip-11-1-111-11
+  $bin_name ssh my-installation-my-cluster ip-11-1-111-11"
+}
+
+print_cluster_usage() {
+  bin_name="$(basename "$0")"
+  echo "Usage:
+  $bin_name cluster create  [ cluster_name ] [ options ]  Create a new cluster
+  $bin_name cluster delete  [ cluster_name ] [ options ]  Delete an existing cluster
+  $bin_name cluster list                                  List all clusters
+  $bin_name cluster status  [ cluster_name ]              Show the status of a cluster
+  $bin_name cluster keep    [ cluster_name ] [ options ]  Keep a cluster until a specified date
+
+Arguments:
+  <cluster_name>  Name of the cluster to manage. If not provided, defaults to the current user name.
+
+Options:
+      --interactive  Use interactive mode to select installation, release, and other options.
+      --nodes-max    Maximum number of nodes in the cluster (default: 10)
+      --nodes-min    Minimum number of nodes in the cluster (default: 3)
+  -u, --until        Date until the cluster should be kept (default: tomorrow)
+
+Examples:
+  gx cluster create --interactive
+  gx cluster delete my-cluster
+  gx cluster list
+  gx cluster status my-cluster
+  gx cluster keep my-cluster --until '2023-12-31'
+  gx cluster create --nodes-max 5 --nodes-min 2 --until '2023-12-31'"
+}
+
+validate_args() {
+  local num_args="$1"; shift
+  local usage_function="$1"; shift
+
+  if "$show_help"; then
+    $usage_function
+    exit 0
+  fi
+
+  if [[ $# -lt "$num_args" ]]; then
+    echo_stderr "ERROR: Missing arguments"
+    $usage_function
+    exit 1
+  fi
+
+  return 0
+}
+
+echo_stderr() {
+    >&2 echo "$@"
 }
 
 log() {
@@ -82,7 +185,7 @@ get_clusters_names() {
 }
 
 create_kubeconfig() {
-  test $# -ge 1 || exit_usage
+  validate_args 1 print_login_usage "$@"
 
   # split words on spaces
   read -r -a values <<< "$(get_clusters_names "$@")"
@@ -132,7 +235,7 @@ create_kubeconfig() {
 }
 
 open_app() {
-  test $# -ge 2 || exit_usage
+  validate_args 2 print_open_usage "$@"
 
   installation="$(get_clusters_names "$1")"
   local app_name="$2"
@@ -152,7 +255,7 @@ open_app() {
 }
 
 ssh_node() {
-  test $# -ge 2 || exit_usage
+  validate_args 2 print_ssh_usage "$@"
 
   # node is always the last argument
   local node="${*: -1}"
@@ -188,23 +291,247 @@ ssh_node() {
   )
 }
 
+get_installation() {
+	interactive=${1:-false}
+
+  echo_stderr -n "> installation: "
+	if $interactive; then
+		name=$(opsctl list installations -s | tr ' ' '\n'|fzf --tac)
+		create_kubeconfig "$name" &>/dev/null
+	fi
+
+	installation="$(kubectl config current-context | cut -d- -f2-)"
+  if [[ -z "$installation" ]]; then
+    echo_stderr "not found!"
+    echo_stderr "> stopping"
+    return 1
+  fi
+  if echo "$installation" | grep -q '-'; then
+    echo_stderr "$installation - invalid!"
+    echo_stderr "> stopping"
+    return 1
+  fi
+  echo_stderr "$installation"
+
+	echo "$installation"
+}
+
+get_release() {
+  local provider="$1"
+	local interactive=${2:-false}
+
+  local release=""
+
+  echo_stderr -n "> release: "
+  if [[ ! "$provider" =~ ^cap.+ ]]; then
+    release="$(get_release_vintage $interactive)"
+  else
+    release="$(get_release_capi $interactive)"
+  fi
+
+  if [[ -z "$release" ]]; then
+    echo_stderr "not found!"
+    echo_stderr "> stopping"
+    return 1
+  fi
+  echo_stderr "$release"
+
+  echo "$release"
+}
+
+get_release_vintage() {
+	interactive=${1:-false}
+
+	releases=$(kubectl get release -ojson)
+	len=$(echo "$releases" | jq -r '.items | length')
+	release_candidates=()
+	for (( i=$len-1; i>=0; i-- )); do
+		name=$(echo "$releases" | jq -r ".items[$i].metadata.name")
+		state=$(echo "$releases" | jq -r ".items[$i].spec.state")
+		ready=$(echo "$releases" | jq -r ".items[$i].status.ready")
+		#echo -e "> name  : $name\n  active: $state\n  ready : $ready"
+		if echo "$name" | grep -vq "-" && [[ "$ready" == "true" ]]; then
+			if $interactive; then
+				release_candidates+=("$name")
+			else
+				echo "$name"
+				return
+			fi
+		fi
+	done
+
+	if $interactive && [[ ${#release_candidates[@]} -gt 0 ]]; then
+		name=$(printf '%s\n' "${release_candidates[@]}" | fzf)
+		echo "$name"
+	fi
+}
+
+get_release_capi() {
+	interactive=${1:-false}
+
+	releases=$(kubectl get release -ojson)
+	len=$(echo "$releases" | jq -r '.items | length')
+	release_candidates=()
+	for (( i=$len-1; i>=0; i-- )); do
+		name=$(echo "$releases" | jq -r ".items[$i].metadata.name")
+		state=$(echo "$releases" | jq -r ".items[$i].spec.state")
+		ready=$(echo "$releases" | jq -r ".items[$i].status.ready")
+		#echo -e "> name  : $name\n  active: $state\n  ready : $ready"
+    if [ $(echo "$name" | grep -o - | wc -l) -lt 2 ] && [[ "$state" == "active" ]]; then
+      release_name="$(echo "$name" | cut -d- -f2)"
+			if $interactive; then
+				release_candidates+=("$release_name")
+			else
+				echo "$release_name"
+				return
+			fi
+		fi
+	done
+
+	if $interactive && [[ ${#release_candidates[@]} -gt 0 ]]; then
+		name=$(printf '%s\n' "${release_candidates[@]}" | fzf)
+		echo "$name"
+	fi
+}
+
+cluster() {
+  validate_args 1 print_cluster_usage "$@"
+
+  local action="$1"; shift
+  local cluster_name="${1:-$USER}"
+  local organization="${USER}"
+
+  cluster_namespace="$(kubectl get cl -Algiantswarm.io/cluster="$cluster_name" -ojson|jq -r '.items[0].metadata.namespace')"
+
+  case "$action" in
+    "list")
+      kubectl gs get clusters -A
+      exit;;
+    "status")
+      clusterctl describe cluster "$cluster_name" --namespace="$cluster_namespace" --show-conditions=all
+      exit;;
+    "keep")
+      kubectl label cluster "$cluster_name" --namespace="$cluster_namespace" --overwrite=true  keep-until="$until"
+      exit;;
+  esac
+
+  installation="$(get_installation $interactive)"
+
+  echo_stderr -n "> provider: "
+  provider="$(opsctl show installation -i "$installation" -ojson | jq -r .Provider)"
+  echo_stderr "$provider"
+
+  release="$(get_release "$provider" $interactive)"
+  release_arg="--release $release"
+
+  echo_stderr -n "> availability zone: "
+  zone="$(kubectl get node -ojson | jq -r '.items[0].metadata.labels["topology.kubernetes.io/zone"]')"
+  if [[ -z "$zone" ]] || [[ "$zone" == "null" ]]; then
+    echo_stderr "not found!"
+    echo_stderr "> stopping"
+    exit 1
+  fi
+  echo_stderr "$zone"
+
+  case "$action" in
+    "create")
+      set -ex
+      kubectl gs template organization \
+        --name "$organization" \
+        | kubectl apply -f - || echo 1
+
+      kubectl gs template cluster \
+        --provider "$provider" \
+        $release_arg \
+        --name "$cluster_name" \
+        --label "keep-until=$until" \
+        --organization "$organization" \
+        --description "$cluster_name test cluster" \
+        | kubectl apply -f -
+
+      if [[ ! "$provider" =~ ^cap.+ ]]; then
+        kubectl-gs template nodepool --provider "$provider" \
+          $release_arg \
+          --cluster-name "$cluster_name" \
+          --availability-zones "$zone" \
+          --organization "$organization" \
+          --description "$cluster_name nodepool" \
+          --nodes-max "$nodes_max" \
+          --nodes-min "$nodes_min" \
+          | kubectl apply -f -
+      fi
+      ;;
+    "delete")
+      set -ex
+      if [[ ! "$provider" =~ ^cap.+ ]]; then
+        kubectl-gs template nodepool --provider "$provider" \
+          --release "$release" \
+          --cluster-name "$cluster_name" \
+          --availability-zones "$zone" \
+          --organization "$organization" \
+          --description "$cluster_name nodepool" \
+          --nodes-max "$nodes_max" \
+          | kubectl delete --wait=false --ignore-not-found=true -f - || echo 1
+      fi
+
+      kubectl gs template cluster \
+        --provider "$provider" \
+        --release "$release" \
+        --name "$cluster_name" \
+        --organization "$organization" \
+        --description "$cluster_name test cluster" \
+        | kubectl delete --wait=false --ignore-not-found=true -f - || echo 1
+      ;;
+    *)
+      echo "invalid action: $action"
+      exit 1;;
+  esac
+
+  set +x
+
+  echo "> success"
+}
+
 main() {
-  # Require at least one argument
-  [[ $# -lt 1 ]] && exit_usage
+  interactive=false
+  nodes_max=10
+  nodes_min=3
+  until=$(date -d tomorrow --utc +"%Y-%m-%d")
+  show_help=false
 
   # Process arguments
+  args=()
   while [[ $# -gt 0 ]]; do
     case $1 in
       -h|--help)
         # Display help message and exit.
-        show_help; exit;;
+        show_help=true;;
+      --interactive)
+        interactive=true;;
+      --nodes-max)
+        [[ -z "${2-}" ]] && echo "ERROR: $1 requires an argument." >&2 && exit 1
+        nodes_max="$2"; shift;;
+      --nodes-min)
+        [[ -z "${2-}" ]] && echo "ERROR: $1 requires an argument." >&2 && exit 1
+        nodes_min="$2"; shift;;
+      -u|--until)
+        [[ -z "${2-}" ]] && echo "ERROR: $1 requires an argument." >&2 && exit 1
+        until=$(date -d "$2" --utc +"%Y-%m-%d"); shift;;
       -?*)
         echo "WARN: Unknown option $1" >&2;;
       *)
-        break;; # No more options
+        args+=("$1");;
     esac
     shift
   done
+
+  set -- "${args[@]}"
+
+  # Require at least one argument
+  if [[ $# -lt 1 ]]; then
+    print_usage
+    exit 0
+  fi
 
   case "$1" in
     open)
@@ -213,6 +540,9 @@ main() {
     ssh)
       shift
       ssh_node "$@";;
+    cluster)
+      shift
+      cluster "$@";;
     login)
       shift;& # fallthrough
     *)
