vpn: wait for actual connection, report real status

diff --git a/.local/bin/vpn b/.local/bin/vpn
--- a/.local/bin/vpn
+++ b/.local/bin/vpn
@@ -51,12 +51,22 @@ ACTION="${1:-status}"
 
 if [ "${ACTION}" == "status" ]; then
 	for connection in $(list_connections); do
-		if current_status="$(nmcli --terse --get-values GENERAL.STATE connection show "${connection}" 2>/dev/null)"; then
-			status="$(echo "$current_status" | grep -q 'activated' && echo 'on' || echo 'off')"
+		# OpenVPN process status
+		if [ -f "/var/run/${connection}.pid" ]; then
+			pid="$(cat "/var/run/${connection}.pid")"
+			openvpn_status="active"
 		else
-			status="not-configured"
+			pid=""
+			openvpn_status="inactive"
 		fi
-		echo "> ${connection} ${status}"
+
+		# NetworkManager connection status
+		if current_status="$(nmcli --terse --get-values GENERAL.STATE connection show "${connection}" 2>/dev/null)"; then
+			nm_status="$(echo "$current_status" | grep -q 'activated' && echo 'on' || echo 'off')"
+		else
+			nm_status="not-configured"
+		fi
+		echo -e "> ${connection}\t${openvpn_status}  \t(${nm_status}\tpid:${pid})"
 	done
 
 	exit 0
@@ -66,20 +76,44 @@ if [ "${ACTION}" == "on" ]; then
 	connection_prefix="${2:-}"
 	connection="$(get_connection "$connection_prefix")"
 
-	echo "> enable ${connection}"
-	nmcli connection up "${connection}"
+	echo -n "> starting ${connection} ."
+	nmcli connection up "${connection}" 1>/dev/null
 
-	exit 0
+	for i in $(seq 1 5); do
+		if ip link show up "tun-gs-${connection%.*}" &>/dev/null; then
+			echo
+			echo "> connected (pid: $(cat /var/run/${connection}.pid))"
+			exit 0
+		fi
+		echo -n "."
+		sleep 1
+	done
+
+        echo
+        echo "> failed"
+	exit 1
 fi
 
 if [ "${ACTION}" == "off" ]; then
 	connection_prefix="${2:-}"
 	connection="$(get_connection "$connection_prefix")"
 
-	echo "> disable ${connection}"
-	nmcli connection down "${connection}"
+	echo -n "> stopping ${connection} ."
+	nmcli connection down "${connection}" 1>/dev/null
 
-	exit 0
+	for i in $(seq 1 5); do
+		if ! ip link show up "tun-gs-${connection%.*}" &>/dev/null; then
+			echo
+			echo "> disconnected"
+			exit 0
+		fi
+		echo -n "."
+		sleep 1
+	done
+
+        echo
+        echo "> failed"
+	exit 1
 fi
 
 if [ "${ACTION}" == "setup" ]; then
